version: '{build}'

platform:
- x64

clone_depth: 5
cache:
- '%LOCALAPPDATA%\Yarn'
- '%USERPROFILE%\.electron'
- node_modules

init:
- git config --global core.autocrlf input
- git config --system core.longpaths true

install:
- ps: Install-Product node 10 x64
- npm install yarn@1.2.1 -g
- yarn install
- ps: . .\tools\install-arduinocli.ps1

build_script:
- yarn run build
- ps: . .\tools\appveyor.ps1

test: off
